#!/bin/sh

prefix=$( dirname "$0" )
usage="\
Uso: gamelib-config [--cflags] [--libs] [--static-libs] [--builddir] [--platform]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

# Preparar configuracion
uname=$( uname )
unamem=$( uname -m )
gcctarget=$( gcc -v 2>&1 | grep "Target:" | cut --delimiter=' ' --fields=2 )
if test $# -gt 0; then
	if test $1 = "emscripten"; then
		uname="EMSCRIPTEN"
		unamem="EMSCRIPTEN"
		shift
	fi
fi
case "$uname" in
	*MINGW* | *MSYS*)
		# Configuracion de Win32/Mingw
		libs="-L/mingw/lib -lopengl32 -lSDL"
		cflags="-g -mwindows -D_GNU_SOURCE=1"
		builddir="build-$gcctarget"
		platform="$gcctarget"
		exeextension=".exe"
		;;
	*EMSCRIPTEN*)
		# Configuracion de Emscripten
		libs=""
		cflags="-s FULL_ES2=1 -s ASM_JS=1 -Wno-implicit-function-declaration"
		builddir="build-emscripten"
		platform="emscripten"
		exeextension=".html"
		;;
	*)
		# Configuracion de Linux
		libs="-lSDL -lpthread -L/usr/X11R6/lib -L/usr/lib -lm -lGL -lX11"
		cflags="-Wall -g -I/usr/include/ -I/usr/include/SDL/ -I/usr/X11R6/include/"
		builddir="build-$gcctarget"
		platform="$gcctarget"
		exeextension=""
		;;
esac

while test $# -gt 0; do
  case $1 in
    --cflags)
      echo "$cflags -I$prefix/GameLib"
      ;;
    --libs)
      echo "$libs"
      ;;
    --static-libs)
      echo "$prefix/$builddir/libgame.a"
      ;;
    --builddir)
      echo "$builddir"
      ;;
    --platform)
      echo "$platform"
      ;;
    --exe-extension)
      echo "$exeextension"
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
