CC= i486-mingw32-gcc
LAUNCHER=
RM=rm -rf

LIBS= -L/usr/i486-mingw/lib -D_GNU_SOURCE=1 -Dmain=SDL_main -lopengl32
CFLAGS= -I/usr/i486-mingw/include  -lmingw32 -lSDLmain -lSDL -mwindows
LDFLAGS=

RESULT=game.exe
BUILDDIR=build-mingw

include Makefile.common


