CC=gcc
LAUNCHER=
RM=rm -rf

LIBS=-I/mingw/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -lopengl32
CFLAGS= -L/mingw/lib -lmingw32 -lSDLmain -lSDL -mwindows -g
LDFLAGS=

RESULT=game.exe
BUILDDIR=build-mingw

include Makefile.common


