CC       := gcc
AR       := ar
LAUNCHER :=
RM       := rm -rf
MKDIR    := mkdir
ECHO     := echo
SLASH    := /

LIBS    := -L/mingw/lib -lopengl32 -lSDL -lm
#CFLAGS  := -I/mingw/include -g -mwindows -D_GNU_SOURCE=1
CFLAGS  := -g -mwindows -D_GNU_SOURCE=1 -DWIN32
LDFLAGS := -g -mwindows -D_GNU_SOURCE=1

RES_GAMELIB := libgame.a
RES_GAME    := game.exe
BUILDDIR    := build-$(shell gcc -v 2>&1 | grep "Target:" | cut --delimiter=' ' --fields=2)

include Makefile.common


